env:
  browser: true
  es6: true
extends:
  - google
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - lib/
rules:
  require-jsdoc: 0
  valid-jsdoc: 0
  no-multi-spaces:
    - error
    - ignoreEOLComments: true
  block-spacing:
    - error
    - always
  indent: off # Let clang-format take care of indentation
